apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels: #this labels relate dto replica set resources
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: #this is the syntax replica set uses to find which pod should be scaled and maintained
      tier: frontend
  template: # pod template,labels are related to pod
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx