---
apiVersion: v1
kind: ConfigMap
metadata:
 name: user-config
data:
 MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
 MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
 name: user-secret
type: Opaque
data:
 username: c212YWt1bWFy 
 password: c212YWt1bWFyMTIz 
---
apiVersion: v1
kind: Pod
metadata: 
 name: user
 labels: 
  name: user
  tier: db
spec:
 containers:
 - name: user
   imagePullPolicy: Always
   image: sekharmanduri/user:k8
   envFrom:
   - configMapRef:
     name: user-config
   - secretRef:
     name: user-secret
   ports:
    - containerPort: 3306
   resources:
    requests:
     cpu: "100m"
     memory: "128Mi"
   limits:
     cpu: "100m"
     memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata: 
 name: user
spec:
 selector:
  name: user
  tier: frontend
 ports:
  - protocol: TCP
    port: 80
    targetPort: 3306
