---
apiVersion: v1
kind: Pod
metadata: 
 name: mongodb
 labels: 
  name: mongodb
  tier: db
spec:
 containers:
 - name: mongodb
   imagePullPolicy: Always
   image: sekharmanduri/web:v1
   resources:
    requests:
     cpu: "100m"
     memory: "128Mi"
    limits:
     cpu: "100m"
     memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata: 
 name: web-service
spec:
 type: LoadBalancer
 selector:
  name: web
  tier: frontend
 ports:
  - protocol: TCP
    port: 80
    targetPort: 80